Enable stacked recurrent layers in Disassembler

diff --git a/autotune b/autotune
--- a/autotune
+++ b/autotune
@@ -12,6 +12,7 @@ model_name="$1"
 data_dir="${here}/data"
 model_dir="${data_dir}/${model_name}"
 grid_dir="${model_dir}/grids"
+log_dir="${model_dir}/logs"
 log_path="${data_dir}/mldisasm.log"
 config_path="${model_dir}/config.json"
 config_bak="${config_path}~"
@@ -34,9 +35,10 @@ for grid in "${grid_dir}"/*; do
     echo "}" >>"${config_path}"
     # Select parameters from the grid.
     "${here}/tune" "${model_name}"
-    if [[ $? -ne 0 ]]; then
+    ret=$?
+    if [[ $ret -ne 0 ]]; then
         # If tune failed, restore backed up config and quit.
-        echo "$0: tune returned error code: $?" >&2
+        echo "$0: tune returned error code: $ret" >&2
         cp   "${config_bak}" "${config_path}"
         exit 1
     fi
